In [60]:
import pandas as pd
import numpy as np

In [42]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [44]:
df

,cgpa,profile_score,placed
0,8,8,1
1,7,9,1
2,6,10,0
3,5,5,0


In [8]:
import tensorflow 
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [14]:
model = Sequential()

model.add(Dense(2,activation = 'sigmoid',input_dim = 2))
model.add(Dense(1,activation = 'sigmoid'))
          
          

/opt/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [46]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29 (120.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 20 (84.00 B)

In [48]:
model.get_weights()

[array([[0.2530665 , 0.2530665 ],
        [0.24494453, 0.24494453]], dtype=float32),
 array([0.1501937, 0.1501937], dtype=float32),
 array([[0.30019763],
        [0.30019763]], dtype=float32),
 array([0.19377911], dtype=float32)]

In [50]:
new_weights = [np.array([[0.1 , 0.1 ],
        [0.1  , 0.1]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1 ],
        [0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

In [52]:
model.set_weights(new_weights)

In [54]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [56]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'binary_crossentropy',optimizer = optimizer)

In [58]:
b

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 569us/step - loss: 0.7173
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 415us/step - loss: 0.7024
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - loss: 0.7163
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 578us/step - loss: 0.7128
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 608us/step - loss: 0.6741
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 822us/step - loss: 0.7060
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 593us/step - loss: 0.6723
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 571us/step - loss: 0.7157
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 497us/step - loss: 0.6840
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - loss: 0.6587
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - loss: 0.7019
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 479us/step - loss: 0.6581
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 521us/step - loss: 0.7278
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - loss: 0.6592
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 547us/step - loss: 0.6584
Epoch 16/50
4/4 ━━━