In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

In [2]:
a = torch.rand(size=(7,7))
a

tensor([[0.3142, 0.2241, 0.3351, 0.0139, 0.9387, 0.9915, 0.7107],
        [0.8146, 0.4483, 0.8263, 0.7478, 0.2326, 0.8766, 0.6250],
        [0.6742, 0.8808, 0.9108, 0.1090, 0.0750, 0.7690, 0.3610],
        [0.7448, 0.7461, 0.7662, 0.7675, 0.6507, 0.3200, 0.0011],
        [0.8635, 0.9365, 0.2140, 0.2602, 0.0473, 0.5437, 0.0841],
        [0.7487, 0.6891, 0.6476, 0.3750, 0.3133, 0.3261, 0.6541],
        [0.9261, 0.1508, 0.1725, 0.5783, 0.0113, 0.7169, 0.6885]])

In [4]:
b = torch.rand(size=(1,7))
b

tensor([[0.5438, 0.9653, 0.3400, 0.8782, 0.0760, 0.1820, 0.3274]])

In [7]:
mul = torch.matmul(a,b.T)
mul

tensor([[0.9978],
        [2.1953],
        [1.8860],
        [2.1678],
        [1.8049],
        [1.9191],
        [1.5724]])

In [10]:
random_seed = 0

torch.manual_seed(random_seed)
random_A = torch.rand(7,7)

torch.manual_seed(random_seed)
random_B = torch.rand(1,7)

mul1 = torch.matmul(random_A,random_B.T)
mul1,mul1.shape



(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [15]:
random_seed = 7

torch.manual_seed(random_seed)
c = torch.rand(1,1,1,10)
c,c.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [16]:
d = torch.squeeze(c)
d,d.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))